# This workflow will do a release
# For more information see: https://github.com/marketplace/actions/create-release

name: Release

on:
  push:
    branches:
      - 'feature/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm run build-prod-ci
      - run: npm run create-zip
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/webjs-starterkit/cimon-web.zip"
          tag: "RELEASE"
          token: ${{ secrets.GITHUB_TOKEN }}
