# This workflow will do a release
# For more information see: https://github.com/marketplace/actions/create-release

name: Release

on:
  push:
    branches:
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: sudo apt-get update
      - run: sudo apt-get install -y libgbm-dev
      - run: npm ci
      - run: npm run build --if-present
#      - run: ls
#      - run: echo "::set-env name=NOW::$(date +'%Y-%m-%dT%H:%M:%S')"
#      - uses: ncipollo/release-action@v1
#        with:
#          artifacts: "dist/webjs-starterkit/cimon-web.zip"
#          tag: $NOW
#          token: ${{ secrets.GITHUB_TOKEN }}
